#!/bin/sh
#********************************************************************#
#  Easy Bootstrap Installer - Uninstall                              #
#  Description: automatic bootstrap installer for synology nas       #
#  Author:      QTip from the german Synology support forum          #
#  Copyright:   2015-2016 by QTip                                    #
#  License:     GNU GPLv3 (see LICENSE)                              #
#  ----------------------------------------------------------------  #
#  Version:     0.2 - 19/12/2015                                     #
#  for more information check the changelog                          #
#********************************************************************#

[ -f /tmp/${SYNOPKG_PKGNAME}.upgrade ] && exit 0

PKG_VOL_TMP=/volume1/@tmp
if [ "${pkgwizard_remove_bootstrap}" == "true" -a -d ${PKG_VOL_TMP}/ebi/VirtualBox ] ; then
     /bin/mkdir -p /opt
     /bin/mv -f ${PKG_VOL_TMP}/ebi/VirtualBox /opt
fi
exit 0
