#!/bin/sh
#PATH="/opt/bin:/opt/sbin:$PATH"

LOG="/var/packages/${SYNOPKG_PKGNAME}/log"
WMTMP="\/`echo ${SYNOPKG_PKGDEST} | /usr/bin/cut -d'/' -f2`\/@tmp\/.webmin"
WMCONFFILE="/var/packages/${SYNOPKG_PKGNAME}/target/etc/config"
DSMLANGUAGE=${SYNOPKG_DSM_LANGUAGE}

if [ "$DSMLANGUAGE" = "def" ] ; then
     DSMLANGUAGE="enu"
fi

case $DSMLANGUAGE in
ger)
	WMLANG="de"  #german
;;
enu)
	WMLANG="en"  #english US
;;
chs)
	WMLANG="zh"  #chinese simplified
;;
csy)
	WMLANG="cs"  #czech
;;
jpn)
	WMLANG="jp"  #japan
;;
krn)
	WMLANG="ko"  #korean
;;
dan)
	WMLANG="da"  #danish
;;
fre)
	WMLANG="fr"  #french
;;
ita)
	WMLANG="it"  #italian
;;
nld)
	WMLANG="nl"  #dutch
;;
nor)
	WMLANG="no"  #norwegian
;;
plk)
	WMLANG="pl"  #polish
;;
rus)
	WMLANG="ru"  #russian
;;
spn)
	WMLANG="sp"  #spanish
;;
sve)
	WMLANG="sv"  #swedish
;;
hun)
	WMLANG="hu"  #hungarian
;;
trk)
	WMLANG="tr"  #turkish
;;
ptg)
	WMLANG="pt"  #portuguese european
;;
esac
if [ ! -f "/tmp/${SYNOPKG_PKGNAME}.upgrade" ] ; then
     mkdir -p /var/log/webmin/output
     if [ "$WMLANG" = "de" ] ; then
          /bin/cat /var/packages/${SYNOPKG_PKGNAME}/scripts/hint_de.txt > $SYNOPKG_TEMP_LOGFILE
     else
          /bin/cat /var/packages/${SYNOPKG_PKGNAME}/scripts/hint_en.txt > $SYNOPKG_TEMP_LOGFILE
     fi
fi

# add recommended packages if /opt/bin/ipkg exist
if [ -f "/opt/bin/ipkg" -a ! -f "/opt/bin/man"] ; then
	if [ "$WMLANG" = "de" ] ; then
	   echo "IPKG erkannt, installiere empfohlene Pakete ...<br>" > $SYNOPKG_TEMP_LOGFILE
	else
	   echo "IPKG detected, installing recommended packages ...<br>" > $SYNOPKG_TEMP_LOGFILE
	fi
	/opt/bin/ipkg install coreutils git git-manpages dstat man man-pages lm-sensors iptables mc perl-net-ssleay lsof gcc make
	sed -i 's/ssl=.*/ssl=1' /var/packages/${SYNOPKG_PKGNAME}/target/etc/miniserv.conf
fi

export WMLANG
cd /var/packages/${SYNOPKG_PKGNAME}/target/scripts 
./install.sh >> $SYNOPKG_TEMP_LOGFILE 2>&1
if [ $? == "0" ] ; then
	[ -f "/opt/sbin/makewhatis" ] && nohup /opt/sbin/makewhatis /opt/man /opt/share/man /volume1/@optware/man /volume1/@optware/share/man &
	sed -i '/Failed to determine/d' $SYNOPKG_TEMP_LOGFILE
else
	exit 1
fi
