#!/bin/sh
#PATH="/opt/bin:/opt/sbin:$PATH"
LOG="/var/packages/${SYNOPKG_PKGNAME}/log"
WMTMP="\/`echo ${SYNOPKG_PKGDEST} | /usr/bin/cut -d'/' -f2`\/@tmp\/.webmin"
WMCONFFILE="/var/packages/${SYNOPKG_PKGNAME}/target/etc/config"
DSMLANGUAGE=${SYNOPKG_DSM_LANGUAGE}

if [ "$DSMLANGUAGE" = "def" ] ; then
     DSMLANGUAGE="enu"
fi

case $DSMLANGUAGE in
ger)
	WMLANG="de"  #german
;;
enu)
	WMLANG="en"  #english US
;;
chs)
	WMLANG="zh"  #chinese simplified
;;
csy)
	WMLANG="cs"  #czech
;;
jpn)
	WMLANG="jp"  #japan
;;
krn)
	WMLANG="ko"  #korean
;;
dan)
	WMLANG="da"  #danish
;;
fre)
	WMLANG="fr"  #french
;;
ita)
	WMLANG="it"  #italian
;;
nld)
	WMLANG="nl"  #dutch
;;
nor)
	WMLANG="no"  #norwegian
;;
plk)
	WMLANG="pl"  #polish
;;
rus)
	WMLANG="ru"  #russian
;;
spn)
	WMLANG="sp"  #spanish
;;
sve)
	WMLANG="sv"  #swedish
;;
hun)
	WMLANG="hu"  #hungarian
;;
trk)
	WMLANG="tr"  #turkish
;;
ptg)
	WMLANG="pt"  #portuguese european
;;
esac
if [ ! -f "/tmp/${SYNOPKG_PKGNAME}.upgrade" ] ; then
     mkdir -p /var/log/webmin/output
     if [ "$DSMLANGUAGE" = "ger" ] ; then
          /bin/cat /var/packages/${SYNOPKG_PKGNAME}/scripts/hint_de.txt > $SYNOPKG_TEMP_LOGFILE
     else
          /bin/cat /var/packages/${SYNOPKG_PKGNAME}/scripts/hint_en.txt > $SYNOPKG_TEMP_LOGFILE
     fi
fi
cd /var/packages/${SYNOPKG_PKGNAME}/target/scripts 
./install.sh >> $SYNOPKG_TEMP_LOGFILE 2>&1
exit $?
