#!/bin/sh
#********************************************************************#
#  Easy Bootstrap Installer - Upgrade                                #
#  Description: automatic bootstrap installer for synology nas       #
#  Author:      QTip from the german Synology support forum          #
#  Copyright:   2015-2016 by QTip                                    #
#  License:     GNU GPLv3 (see LICENSE)                              #
#  ----------------------------------------------------------------  #
#  Version:     0.31 - 07/06/2016                                    #
#  for more information check the changelog                          #
#********************************************************************#

PKG_VOL_TMP="/`echo ${SYNOPKG_PKGDEST} | /usr/bin/cut -d'/' -f2`/@tmp"

/bin/mkdir -p ${PKG_VOL_TMP}/ebi
/bin/cp -f ${SYNOPKG_PKGDEST}/*_installed ${PKG_VOL_TMP}/ebi
/bin/cp -f ${SYNOPKG_PKGDEST}/*link ${PKG_VOL_TMP}/ebi
/bin/cp -f ${SYNOPKG_PKGDEST}/*_priority ${PKG_VOL_TMP}/ebi
/bin/touch /tmp/${SYNOPKG_PKGNAME}.upgrade
exit 0
